-- MySQL Script generated by MySQL Workbench
-- Thu Mar 17 09:39:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Piltzintli
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Piltzintli
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Piltzintli` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `Piltzintli` ;

-- -----------------------------------------------------
-- Table `Piltzintli`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`roles_id`) REFERENCES roles(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`padres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`padres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(30) NOT NULL,
  `numero` VARCHAR(8) NOT NULL,
  `colonia` VARCHAR(25) NOT NULL,
  `codigo` VARCHAR(5) NOT NULL,
  `municipio` VARCHAR(40) NOT NULL,
  `estado` VARCHAR(25) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `mail` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `escolaridad` VARCHAR(14) NOT NULL,
  `diagnostico` VARCHAR(45) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `padres_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`padres_id`) REFERENCES padres(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`especialistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`especialistas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `profesion` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`tipos_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`tipos_consulta` (
  `id` INT NOT NULL,
  `tipo_consulta` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`terapias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`terapias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `terapia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`consultas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `pacientes_id` INT NOT NULL,
  `especialistas_id` INT NOT NULL,
  `tipos_consulta_id` INT NOT NULL,
  `terapias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`pacientes_id`) REFERENCES pacientes(id),
  FOREIGN KEY (`especialistas_id`) REFERENCES especialistas(id),
  FOREIGN KEY (`tipos_consulta_id`) REFERENCES tipos_consulta(id),
  FOREIGN KEY (`terapias_id`) REFERENCES terapias(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `consultas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`consultas_id`) REFERENCES consultas(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_articulo` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `cantidad_deseable` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;