-- MySQL Script generated by MySQL Workbench
-- Thu Mar 17 12:07:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Piltzintli
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Piltzintli
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Piltzintli` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `Piltzintli` ;


-- -----------------------------------------------------
-- Table `Piltzintli`.`padre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`padre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `cp` VARCHAR(5) NOT NULL,
  `municipio` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` VARCHAR(50) NOT NULL,
  `escolaridad` VARCHAR(14) NOT NULL,
  `diagnostico` VARCHAR(40) NULL,
  `padre_id` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`padre_id`) REFERENCES padre(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`especialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`especialista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NOT NULL,
  `profesion` VARCHAR(40) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `especialidad` VARCHAR(40) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(80) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `paciente_id` INT NOT NULL,
  `especialista_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`paciente_id`) REFERENCES paciente(id),
  FOREIGN KEY (`especialista_id`) REFERENCES especialista(id))
ENGINE = InnoDB;