-- MySQL Script generated by MySQL Workbench
-- Thu Mar 17 12:07:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Piltzintli
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Piltzintli
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Piltzintli` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `Piltzintli` ;

-- -----------------------------------------------------
-- Table `Piltzintli`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`rol_id`) REFERENCES rol(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`padre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`padre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `cp` VARCHAR(5) NOT NULL,
  `municipio` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` VARCHAR(50) NOT NULL,
  `escolaridad` VARCHAR(14) NOT NULL,
  `diagnostico` VARCHAR(40) NULL,
  `padre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`padre_id`) REFERENCES padre(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`especialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`especialista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NOT NULL,
  `profesion` VARCHAR(40) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `especialidad` VARCHAR(40) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(80) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`tipo_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`tipo_consulta` (
  `id` INT NOT NULL,
  `tipo_consulta` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`terapia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`terapia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `terapia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `paciente_id` INT NOT NULL,
  `especialista_id` INT NOT NULL,
  `tipo_consulta_id` INT NOT NULL,
  `terapia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`paciente_id`) REFERENCES paciente(id),
  FOREIGN KEY (`especialista_id`) REFERENCES especialista(id),
  FOREIGN KEY (`tipo_consulta_id`) REFERENCES tipo_consulta(id),
  FOREIGN KEY (`terapia_id`) REFERENCES terapia(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `consulta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`consulta_id`) REFERENCES consulta(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_articulo` VARCHAR(50) NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `cantidad_deseable` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piltzintli`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piltzintli`.`contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contacto` VARCHAR(70) NOT NULL,
  `padre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`padre_id`) REFERENCES padre(id))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;