/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultas;

import ConexionDB.DbConnection;
import Especialista.DatosEspecialista;
import Menu.Principal;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author 1234
 */
public class modificar_cita extends javax.swing.JFrame {

    DatosCita dc = new DatosCita();

    public modificar_cita() throws IOException {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setResizable(false);

        BufferedImage imagenIcono = ImageIO.read(getClass().getResource("/Recursos/logo_bcklss.png"));
        this.setTitle("Modificaciones Citas");
        this.setIconImage(imagenIcono);

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                int opc = JOptionPane.showConfirmDialog(null, "Regresar al Menú Principal?", "Regresar", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE);

                if (opc == JOptionPane.YES_OPTION) {

                    try {
                        new Menu.Principal().setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    dispose();
                }

            }

        });
        
        try {
            DbConnection conexion;
            Statement estatuto;
            String solicitudSQL;
            ResultSet resultado;

            cbx_Padres.removeAllItems();
            conexion = new DbConnection();
            estatuto = conexion.getConnection().createStatement();

            solicitudSQL = "SELECT id, nombre, apellido_paterno, apellido_materno FROM paciente";
            System.out.println(solicitudSQL);

            resultado = estatuto.executeQuery(solicitudSQL);

            while (resultado.next()) {

                int identificador = resultado.getInt("id");
                String nombre = resultado.getString("nombre");
                String apP = resultado.getString("apellido_paterno");
                String apM = resultado.getString("apellido_materno");

                String complexBuildString = String.valueOf(identificador) + "/" + nombre + " " + apP + " " + apM;
                cbx_Padres.addItem(complexBuildString);

            }

            estatuto.close();
            conexion.desconectar();

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        cbx_Padres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_PadresActionPerformed(evt);
            }
        });

        campo_Observaciones.setEditable(false);
        campo_IDCita.setEditable(false);
        campo_hora.setEditable(false);
        campo_idEspecialista.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_res = new javax.swing.JButton();
        btn_bacck = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campo_hora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campo_idEspecialista = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_Observaciones = new javax.swing.JTextArea();
        campo_IDCita = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        calendario = new com.toedter.calendar.JDateChooser();
        cbx_Padres = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Modificar Cita");

        btn_res.setText("Guardar");
        btn_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resActionPerformed(evt);
            }
        });

        btn_bacck.setText("Regresar");
        btn_bacck.setNextFocusableComponent(campo_hora);
        btn_bacck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bacckActionPerformed(evt);
            }
        });

        jLabel2.setText("Hora: (HH:MM:SS)");

        campo_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_horaActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha:  ");

        campo_idEspecialista.setNextFocusableComponent(btn_res);
        campo_idEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_idEspecialistaActionPerformed(evt);
            }
        });

        jLabel7.setText("Paciente");

        jLabel8.setText("ID Especialista");

        jLabel9.setText("Observaciones");

        campo_Observaciones.setColumns(20);
        campo_Observaciones.setRows(5);
        jScrollPane1.setViewportView(campo_Observaciones);

        campo_IDCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_IDCitaActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de Cita (ID)");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        cbx_Padres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_Padres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_PadresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(cbx_Padres, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(campo_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(campo_IDCita, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(campo_idEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_buscar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_bacck)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_res))))))
                .addGap(18, 80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbx_Padres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(campo_hora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campo_IDCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_idEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bacck)
                    .addComponent(btn_res))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resActionPerformed

        DbConnection conexion;
        Statement estatuto;
        String solicitudSQL;

        String hora = campo_hora.getText();
        String idCita = campo_IDCita.getText();
        String idEspecialista = campo_idEspecialista.getText();
        String observaciones = campo_Observaciones.getText();
        
        java.util.Date fechaCalendario = calendario.getDate();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = df.format(fechaCalendario);
        
        String idPaciente = "";
        String nombreTutor = cbx_Padres.getSelectedItem().toString();

        for (int i = 0; i < nombreTutor.length() - 1; i++) {

            if (nombreTutor.charAt(i) == '0'
                    || nombreTutor.charAt(i) == '1'
                    || nombreTutor.charAt(i) == '2'
                    || nombreTutor.charAt(i) == '3'
                    || nombreTutor.charAt(i) == '4'
                    || nombreTutor.charAt(i) == '5'
                    || nombreTutor.charAt(i) == '6'
                    || nombreTutor.charAt(i) == '7'
                    || nombreTutor.charAt(i) == '8'
                    || nombreTutor.charAt(i) == '9') {

                idPaciente += nombreTutor.charAt(i);
            }

        }

        try {

            conexion = new DbConnection();
            estatuto = conexion.getConnection().createStatement();
            // Agrega la hora y fecha 
            solicitudSQL = "UPDATE consulta SET fecha = '" + fecha + "' , hora = '" + hora + "', paciente_id = '" + idPaciente + "', especialista_id = '" + idEspecialista + "', observaciones = '" + observaciones + "' where id like " + idCita;

            estatuto.executeUpdate(solicitudSQL);
            /// Indica que se a actualizada la agenda de especialistas   
            JOptionPane.showMessageDialog(null, "Cita Modificada con Exito!", "Informacion", JOptionPane.INFORMATION_MESSAGE);

            estatuto.close();
            conexion.desconectar();
            
            campo_IDCita.setText("");
            campo_hora.setText("");
            campo_idEspecialista.setText("");
            campo_Observaciones.setText("");

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al Modificar!", "Informacion", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_btn_resActionPerformed

    private void btn_bacckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bacckActionPerformed
        int opc = JOptionPane.showConfirmDialog(null, "Regresar al Menú Principal?", "Regresar", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (opc == JOptionPane.YES_OPTION) {

            try {
                new Menu.Principal().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
        }
    }//GEN-LAST:event_btn_bacckActionPerformed

    private void campo_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_horaActionPerformed

    private void campo_idEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_idEspecialistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_idEspecialistaActionPerformed

    private void campo_IDCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_IDCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_IDCitaActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        DbConnection conexion;
        Statement estatuto;
        String solicitudSQL;
        ResultSet resultado;
        
        String id = "";
        String nombreTutor = cbx_Padres.getSelectedItem().toString();

        for (int i = 0; i < nombreTutor.length() - 1; i++) {

            if (nombreTutor.charAt(i) == '0'
                    || nombreTutor.charAt(i) == '1'
                    || nombreTutor.charAt(i) == '2'
                    || nombreTutor.charAt(i) == '3'
                    || nombreTutor.charAt(i) == '4'
                    || nombreTutor.charAt(i) == '5'
                    || nombreTutor.charAt(i) == '6'
                    || nombreTutor.charAt(i) == '7'
                    || nombreTutor.charAt(i) == '8'
                    || nombreTutor.charAt(i) == '9') {

                id += nombreTutor.charAt(i);
            }

        }
        
        java.util.Date fechaCalendario = calendario.getDate();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = df.format(fechaCalendario);

        try {
            conexion = new DbConnection();
            estatuto = conexion.getConnection().createStatement();

            solicitudSQL = "SELECT id, fecha, hora, paciente_id, especialista_id, observaciones FROM "
                    + "consulta where paciente_id like " + id + " and fecha like '" + fecha +"'";
            System.out.println(solicitudSQL);

            resultado = estatuto.executeQuery(solicitudSQL);

            while (resultado.next()) {

                campo_IDCita.setText(String.valueOf(resultado.getInt("id")));
                resultado.getString("fecha");
                campo_hora.setText(resultado.getString("hora"));
                resultado.getInt("paciente_id");
                campo_idEspecialista.setText(String.valueOf(resultado.getInt("especialista_id")));
                campo_Observaciones.setText(resultado.getString("observaciones"));
            }

            estatuto.close();
            conexion.desconectar();

            campo_Observaciones.setEditable(true);
            campo_hora.setEditable(true);
            campo_idEspecialista.setEditable(true);

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "No se Encontraron Datos!", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void cbx_PadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_PadresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_PadresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new modificar_cita().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(modificar_cita.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bacck;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_res;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JTextField campo_IDCita;
    private javax.swing.JTextArea campo_Observaciones;
    private javax.swing.JTextField campo_hora;
    private javax.swing.JTextField campo_idEspecialista;
    private javax.swing.JComboBox<String> cbx_Padres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
