/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paciente;


import Menu.*;
import ConexionDB.DbConnection;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author 1234
 */
public class RegistrarPacientes extends javax.swing.JFrame {
    private boolean paciente =false;
    DefaultTableModel modelo = new DefaultTableModel();
    Object fila[] = new Object[3];
    
    /**
     * Creates new form RegistrarPacientes
     */
    public RegistrarPacientes() throws IOException {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        BufferedImage imagenIcono = ImageIO.read(new File("logo_bcklss.png"));
        this.setTitle("Altas Paciente");
        this.setIconImage(imagenIcono);
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                int opc = JOptionPane.showConfirmDialog(null, "Regresar al Menú Principal?", "Regresar", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE);

                if (opc == JOptionPane.YES_OPTION) {

                    try {
                        new Menu.Principal().setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    dispose();
                }

            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textApellidoPaterno = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textEscolaridad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textApellidoMaterno = new javax.swing.JTextField();
        textDiagnostico = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        textFecha = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        MunicipioT = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        EstadoT = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        DireccionT = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        CPT = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        ApellidoPaternoT = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        ApellidoMaternoT = new javax.swing.JTextField();
        NombreT = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pacientestatus = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        jTextField5.setText(".");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1500, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 900));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Pacientes...");

        jLabel3.setText("Nombre:");

        textApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textApellidoPaternoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Borrar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellido Paterno:");

        jLabel5.setText("Apellido Materno:");

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });

        textEscolaridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEscolaridadActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha de nacimiento: ");

        jLabel7.setText("Escolaridad:");

        jLabel8.setText("Diagnostico:");

        textApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textApellidoMaternoActionPerformed(evt);
            }
        });

        textDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDiagnosticoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        textFecha.setEditable(false);
        textFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaActionPerformed(evt);
            }
        });

        jButton3.setText("Insertar Fecha");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("Registrar Padre o Tutor...");

        jLabel35.setText("Municipio:");

        jLabel36.setText("Estado:");

        DireccionT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionTActionPerformed(evt);
            }
        });

        jLabel37.setText("Dirección:");

        jLabel38.setText("Codigo Postal:");

        jLabel39.setText("Apellido Paterno:");

        jLabel40.setText("Apellido Materno:");

        jLabel41.setText("Nombre:");

        jLabel10.setText("Status");

        pacientestatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Activo", "Inactivo" }));
        pacientestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientestatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(EstadoT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(DireccionT, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ApellidoMaternoT, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addComponent(ApellidoPaternoT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(CPT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(113, 113, 113)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MunicipioT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel4)
                                        .addGap(158, 158, 158)
                                        .addComponent(jLabel5)
                                        .addGap(207, 207, 207)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textApellidoPaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(textFecha, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(99, 99, 99)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(pacientestatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(113, 113, 113)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(textDiagnostico)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel36)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel40)
                                .addGap(172, 172, 172)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel41)
                                .addGap(73, 73, 73))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel37)
                                .addGap(197, 197, 197)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel35)
                                .addGap(70, 70, 70))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel6)
                                .addGap(168, 168, 168)
                                .addComponent(jLabel7)
                                .addGap(204, 204, 204)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jLabel1)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pacientestatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel39)
                    .addComponent(jLabel41))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidoMaternoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoPaternoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel35)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MunicipioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstadoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void textEscolaridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEscolaridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEscolaridadActionPerformed

    private void textApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoMaternoActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void textDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDiagnosticoActionPerformed
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       int idTutor=0;
        //Registra los datos del tutor.
       DatosTutorDAO daoTutor = new DatosTutorDAO();
       DatosPadreoTutor mitutor = new DatosPadreoTutor();
       
       Pattern nombre = Pattern.compile("[a-zA-Z]+");
        Matcher letras = nombre.matcher(NombreT.getText());
        Pattern apellidop = Pattern.compile("[a-zA-Z]+");
        Matcher letras1 = apellidop.matcher(ApellidoPaternoT.getText());
        Pattern apellidom = Pattern.compile("[a-zA-Z]+");
        Matcher letras2 = apellidom.matcher(ApellidoMaternoT.getText());
        Pattern codigop = Pattern.compile("\\ d {5}");
        Matcher codigopostalv = codigop.matcher(CPT.getText());
        
       
        if (!NombreT.getText().equalsIgnoreCase("") 
                && !ApellidoPaternoT.getText().equalsIgnoreCase("")
                && !ApellidoMaternoT.getText().equalsIgnoreCase("") 
                && !DireccionT.getText().equalsIgnoreCase("")
                && !CPT.getText().equalsIgnoreCase("") 
                && !MunicipioT.getText().equalsIgnoreCase("")
                && !EstadoT.getText().equalsIgnoreCase("")) {
            
            if (letras.matches()) {
                if (letras1.matches()) {
                    if (letras2.matches()) {
                        if(codigopostalv.matches()){

       mitutor.setNombretutor((NombreT.getText()));
       mitutor.setApellidopaterno(ApellidoPaternoT.getText());
       mitutor.setApellidomaterno(ApellidoMaternoT.getText());
       mitutor.setDireccion(DireccionT.getText());
       mitutor.setCodigopostal(CPT.getText());
       mitutor.setMunicipio(MunicipioT.getText());  
       mitutor.setEstado(EstadoT.getText());  
        idTutor = mitutor.getIdtutor();
       daoTutor.RegistrarDatosTutor(mitutor);
       
                        }else{
                                //el codigo postal esta mal escrito
                                 JOptionPane.showMessageDialog(null, "Codigo Postal Invalido",
                                         "Informacion", JOptionPane.INFORMATION_MESSAGE);
                              }
                    } else {
                                 //el apellido materno esta mal escrito
                                 JOptionPane.showMessageDialog(null, "Apellido Materno Invalido",
                                         "Informacion", JOptionPane.INFORMATION_MESSAGE);
                          }

                } else {
                          //el apellido paterno esta mal escrito
                             JOptionPane.showMessageDialog(null, "Apellido Paterno Invalido",
                                     "Informacion", JOptionPane.INFORMATION_MESSAGE);
                        }

            } else {
                    //el nombre esta mal escrito
                     JOptionPane.showMessageDialog(null, "Nombre Invalido",
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    }

       } else {
            //Mensaje de que llene todos los campos
            JOptionPane.showMessageDialog(null, "No se puede realizar el registro por que algunos de los campos estan vacios.",
                    "Informacion campos vacios", JOptionPane.INFORMATION_MESSAGE);
        }
        
        //Registra los datos del paciente.
        PacientesDAO daoPaciente = new PacientesDAO();
       Pacientes mipaciente = new Pacientes();
       
       Pattern nombreP = Pattern.compile("[a-zA-Z]+");
        Matcher letrasP = nombre.matcher(textNombre.getText());
        Pattern apellidopP = Pattern.compile("[a-zA-Z]+");
        Matcher letras1P = apellidop.matcher(textApellidoPaterno.getText());
        Pattern apellidomP = Pattern.compile("[a-zA-Z]+");
        Matcher letras2P = apellidom.matcher(textApellidoMaterno.getText());
        
       
        if (!textNombre.getText().equalsIgnoreCase("") && !textApellidoPaterno.getText().equalsIgnoreCase("")
                && !textApellidoMaterno.getText().equalsIgnoreCase("") && !textFecha.getText().equalsIgnoreCase("")
                && !textEscolaridad.getText().equalsIgnoreCase("") && !textDiagnostico.getText().equalsIgnoreCase("")) {
            
            if (letras.matches()) {
                if (letras1.matches()) {
                    if (letras2.matches()) {

       mipaciente.setNombre((textNombre.getText()));
       mipaciente.setApellido_paterno(textApellidoPaterno.getText());
       mipaciente.setApellido_materno(textApellidoMaterno.getText());
       mipaciente.setFecha_nacimiento(textFecha.getText());
       mipaciente.setEscolaridad(textEscolaridad.getText());
       mipaciente.setDiagnostico(textDiagnostico.getText());
       mipaciente.setPadre_id(idTutor);
       //ifs para ver la seleccion del status(combobox)
        if (pacientestatus.getSelectedItem() == "Activo") {
                    mipaciente.setStatus(1);
        }

            if (pacientestatus.getSelectedItem() == "Inactivo") {
                 mipaciente.setStatus(0);
            }
       daoPaciente.RegistrarPacientes(mipaciente);
      //se activa la variable paciente para que el usuario no pueda registrar un padre antes de registrar al paciente
       paciente=true;
                    } else {
                        //el apellido materno esta mal escrito
                        JOptionPane.showMessageDialog(null, "Apellido Materno Invalido",
                                "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    }

                } else {
                    //el apellido paterno esta mal escrito
                    JOptionPane.showMessageDialog(null, "Apellido Paterno Invalido",
                            "Informacion", JOptionPane.INFORMATION_MESSAGE);
                }

            } else {
                //el nombre esta mal escrito
                JOptionPane.showMessageDialog(null, "Nombre invalido",
                        "Informacion", JOptionPane.INFORMATION_MESSAGE);
            }
       } else {
            //Mensaje de que llene todos los campos
            JOptionPane.showMessageDialog(null, "No se puede realizar el registro por que algunos de los campos estan vacios.",
                    "Informacion campos vacios", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       // limpia los campos del paciente.
        textNombre.setText("");
        textApellidoPaterno.setText("");
        textApellidoMaterno.setText("");
        textFecha.setText("");
        textEscolaridad.setText("");
        textDiagnostico.setText("");
      //limpia los campos del tutor.
        ApellidoMaternoT.setText("");
        ApellidoPaternoT.setText("");
        NombreT.setText("");
        DireccionT.setText("");
        CPT.setText("");
        MunicipioT.setText("");
        EstadoT.setText("");
       
        //Limpia(remueve) los items del combo
        pacientestatus.removeAllItems();

        //Agrega las estatus para seleccionarlo(para que en automatico te de la opcion "seleccionar")
        pacientestatus.addItem("Seleccionar");
        pacientestatus.addItem("Activado");
        pacientestatus.addItem("Inactivo");
        
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void textFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaActionPerformed
       
    }//GEN-LAST:event_textFechaActionPerformed

    private void textApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoPaternoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String fechaComoCadena = sdf.format(new Date());
        System.out.println(fechaComoCadena);
       textFecha.setText(fechaComoCadena);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DireccionTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionTActionPerformed

    private void pacientestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientestatusActionPerformed

    }//GEN-LAST:event_pacientestatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegistrarPacientes().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(RegistrarPacientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoMaterno;
    private javax.swing.JTextField ApellidoMaterno1;
    private javax.swing.JTextField ApellidoMaterno2;
    private javax.swing.JTextField ApellidoMaternoT;
    private javax.swing.JTextField ApellidoPaterno;
    private javax.swing.JTextField ApellidoPaterno1;
    private javax.swing.JTextField ApellidoPaterno2;
    private javax.swing.JTextField ApellidoPaternoT;
    private javax.swing.JTextField CP;
    private javax.swing.JTextField CP1;
    private javax.swing.JTextField CP2;
    private javax.swing.JTextField CPT;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Direccion1;
    private javax.swing.JTextField Direccion2;
    private javax.swing.JTextField DireccionT;
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField Estado1;
    private javax.swing.JTextField Estado2;
    private javax.swing.JTextField EstadoT;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar1;
    private javax.swing.JButton Guardar2;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Limpiar1;
    private javax.swing.JButton Limpiar2;
    private javax.swing.JTextField Municipio;
    private javax.swing.JTextField Municipio1;
    private javax.swing.JTextField Municipio2;
    private javax.swing.JTextField MunicipioT;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField Nombre2;
    private javax.swing.JTextField NombreT;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox<String> pacientestatus;
    private javax.swing.JTextField textApellidoMaterno;
    private javax.swing.JTextField textApellidoPaterno;
    private javax.swing.JTextField textDiagnostico;
    private javax.swing.JTextField textEscolaridad;
    private javax.swing.JTextField textFecha;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
